### ISSUE TITLE
Handle arguements of the style: --job-name=foo

### ISSUE THREAD

**Issue by BlakeGFitch** [flyingangel/argparser#1]
Hello Sir,

This is a really cool bit of code!

I'd like to be able to use long arguments with hyphens between words in their names. Would that be a simple thing to add?

Also, is it possible to get a list of all arguments found to test if any are passed but not supported?

Thanks for considering!

**Comment by flyingangel** [comment]
Done. Now you can use `$jobName` in camelCase

**Comment by BlakeGFitch** [comment]
Hello Sir,

Thanks so much for this. Any chance to have a list of all the args that have been found to check for ones that are not supported?

Also, would it be possible that -- stops the parsing of args? Some programs work that way where the remaining arguments will be pass along as-is.

I have deployed your code in a couple of cases.

Thanks again.

**Comment by flyingangel** [comment]
Please open a new ticket.

List of args is not needed. All args are meant to be supported. If not and detected by user, I can simply improve the project.

What do you mean by stopping args? If you dont call argparser, it won't parse anything at all. An exemple? => (new ticket)
